Almacen/Almacen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.gestion.urls')),
]

Almacen/apps/gestion/urls.py
from django.urls import path

from . import views

app_name = "gestion"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>', views.show, name="show"),
    path('create', views.create, name="create"),
    path('update/<int:pk>', views.update, name="update"),
    path('delete/<int:pk>', views.delete, name="delete"),
]

Almacen/apps/gestion/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(decimal_places=2, max_digits=10)
    category =models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

Almacen/apps/gestion/forms.py
from django import forms

from .models import Category

class ProductForm(forms.Form):
    title = forms.CharField(label="Title", max_length=255, min_length=1, required=True)
    description= forms.CharField(label="Description", required=True, widget=forms.Textarea(attrs={ 'rows':1, 'cols':20 }))
    price = forms.FloatField(min_value=0.1)
    category = forms.ModelChoiceField(label="Category", queryset=Category.objects.all())

Almacen/apps/gestion/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse, HttpResponseNotFound

from .models import Product
from .forms import ProductForm

# Create your views here.
def index(request):

    products = Product.objects.all()

    paginator = Paginator(products,2)
    
    page_number = request.GET.get('page')

    try:
        products_page = paginator.page(page_number) #get_page ya realiza internamente esta validacion
    except PageNotAnInteger:
        print ("Error page not an integer")
        products_page = paginator.page(1)
    except EmptyPage:
        print ("Error page not found")
        products_page = paginator.page(1)

    return render(request, 'index.html', {'products': products_page})

def show(request, pk):

    """ try:
        product = Product.objects.get(pk=pk)
    except Product.DoesNotExist:
        print ("Error product does not exist")
        #return HttpResponse(status=404)
        return HttpResponseNotFound """
    
    product = get_object_or_404(Product, pk=pk)

    return render(request, 'show.html', {'product': product})

def create(request):
    form = ProductForm()
    if request.method == "POST":
        form = ProductForm(request.POST)
        if form.is_valid():
            print("valido")

            product = Product()

            product.title=form.cleaned_data['title']
            product.description=form.cleaned_data['description']
            product.price=form.cleaned_data['price']
            product.category=form.cleaned_data['category']

            product.save()
            print("product save:", product)
            return redirect('gestion:update', pk=product.id)

        else:
            print("invalido")

    return render(request, 'save.html', {'form': form})

def update(request, pk):
    product = get_object_or_404(Product, pk=pk)
    
    form = ProductForm(initial={'title':product.title,'description':product.description,'price':product.price,'category':product.category})
    
    if request.method == "POST":
        form = ProductForm(request.POST)
        
        if form.is_valid():
            print("valido")

            product.title=form.cleaned_data['title']
            product.description=form.cleaned_data['description']
            product.price=form.cleaned_data['price']
            product.category=form.cleaned_data['category']

            product.save()
            print("product update:", product)

            return redirect('gestion:index')

        else:
            print("invalido")

    return render(request, 'save.html', {'form': form})

def delete(request, pk):

    product = get_object_or_404(Product, pk=pk)
    print("Product delete: ", product)
    product.delete()
    return redirect('gestion:index')

Almacen/apps/gestion/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" 
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" 
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" 
    integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" 
    crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" 
    crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" 
    crossorigin="anonymous"></script>
</head>
<body>
    {% block content %} 
    {% endblock %}
</body>
</html>

Almacen/apps/gestion/templates/index.html
{% extends 'base_generic.html' %}
{% block title %} 
Listado de productos 
{% endblock %}
{% block content %}
    <h1>Productos:</h1>
    <br>
    <ul>
        {% for p in products %}
            <li>
                <p>{{p.title}}</p>
                <a class="link" href="{% url 'gestion:show' p.id %}">More info</a>
                <a class="link" href="{% url 'gestion:update' p.id %}">Update</a>
                <a class="link" href="{% url 'gestion:delete' p.id %}">Delete</a>
            </li>
            <hr>
        {% endfor %}
    </ul>
    <button>
        <a class="link" href="{% url 'gestion:create' %}">Add new product</a>
    </button>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center mt-5"> 
            {% if products.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ products.previous_page_number }}">previous</a>
                </li>
            {% endif %}
            
            {% for i in products.paginator.page_range %}
                {% if i == products.number %}
                    <li class="page-item active">
                        <a class="page-link" href="#">{{i}}</a>
                    </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{i}}">{{i}}</a>
                </li>
                {% endif %}
            {% endfor %}
            
            {% if products.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ products.next_page_number }}">next</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

Almacen/apps/gestion/templates/save.html
{% extends 'base_generic.html'%}

{% block title %} 
Add or update
{% endblock %}

{% block content%}
    <h1>Add new product / Update product</h1>
    <form method="POST">
        {% csrf_token %}

        {{form}}

        <button type="submit">Submit</button>
    </form>
    <br>
    <a class="link" href="{% url 'gestion:index' %}?page=1">Inicio</a>
{% endblock %}

Almacen/apps/gestion/templates/show.html
{% extends 'base_generic.html'%}

{% block title %} 
Producto: {{product.title}} 
{% endblock %}

{% block content%}

    <h1>{{product.title}}</h1>
    <h4>Description:</h4>
    <p>{{product.description}}</p>
    <p>Price: ${{product.price}}</p>
    <p>Category: {{product.category}}</p>

    <hr>
    <a class="link" href="{% url 'gestion:index' %}?page=1">Inicio</a>
{% endblock %}